# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d6fd182c13268701d61dc45f76c735e"
name = "Bidly"
application_url = "https://bidly-auction-admin.onrender.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_product_listings,read_products,write_products,read_draft_orders,write_draft_orders,read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://bidly-auction-backend.onrender.com/auth/shopify/callback"
]

[app_proxy]
url = "https://bidly-auction-backend.onrender.com/apps/bidly"
subpath = "bidly"
prefix = "apps"
