# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Bidly"
client_id = "de32970476f2ecf20d98f9d9b6994c89"
application_url = "https://bidly-auction-backend-2.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_inventory,read_product_listings,read_products,write_customers,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://bidly-auction-backend-2.onrender.com/auth/shopify/callback"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "6sb15z-k1.myshopify.com"

[app_proxy]
url = "https://bidly-auction-backend-2.onrender.com/apps/bidly"
subpath = "bidly"
prefix = "apps"

