# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "698a2d663b3718b47b794bfbd6835ef4"
name = "Bidly"
application_url = "https://bidly-backend.hiiiiiiiiiii.com"
embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://bidly-backend.hiiiiiiiiiii.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_product_listings,read_products,write_products,read_draft_orders,write_draft_orders,read_orders,read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://bidly-backend.hiiiiiiiiiii.com/auth/shopify/callback"
]

[app_proxy]
url = "https://bidly-backend.hiiiiiiiiiii.com/apps/bidly"
subpath = "bidly"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bidly-2.myshopify.com"